### ISSUE TITLE
{ "mutable-content" : 1 } in Localytics Push Payload

### ISSUE THREAD

**Issue by pooniawalla** [localytics/ios-samples#1]
How are you setting  { "mutable-content" : 1 } from Localytics dashboard, so that the Notification Payload looks like > 

_{
    "aps" : {
        "alert" : "Sample text message for notification",
        **"mutable-content" : 1**
    }
    "image-url" : "https://sample.com/image.jpg"
}_

If "mutable-content" key set then it appears outside "aps" object like >

_{
    "aps" : {
        "alert" : "Sample text message for notification"
    }
    **"mutable-content" : 1,**
    "image-url" : "https://sample.com/image.jpg"
}_

**Comment by ryang1428** [comment]
@Mriegel Same question as above. We have a custom key/value pair "attachment-url" since the web does not support the rich notifications yet. But, upon sending that along, which our app has the extension to handle, the push payload does not include the required `mutable-content: 1` needed. How could we pass that along with the push so we can support rich notifications?

**Comment by Mriegel** [comment]
This is now fully supported both through the dashboard and through the [Push API](https://docs.localytics.com/dev/push-api.html#concepts).
